Section "InputClass"
    Identifier "Touchpad tap-to-click"
    MatchIsTouchpad "on"
    MatchDriver "libinput"
    Option "NaturalScrolling" "true"
    Option "Tapping" "true"
    Option "TappingButtonMap" "lrm"
EndSection
